import { Inter as FontSans } from 'next/font/google';

import { cn } from '@hendaz/ds/utils';

import { ConvexClientProvider } from './ConvexClientProvider';

import './global.css';

export const metadata = {
  description: 'Generated by create-nx-workspace',
  title: 'Welcome to file-drive',
};

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
        <ConvexClientProvider>{children}</ConvexClientProvider>
      </body>
    </html>
  );
}
