import { Inter as FontSans } from 'next/font/google';

import { Toaster } from '@hendaz/ds/ui-kit/lib/ui/toaster';
import { cn } from '@hendaz/ds/utils';

import { ConvexClientProvider } from './ConvexClientProvider';
import Footer from './footer';
import Header from './header';

import './global.css';

export const metadata = {
  description: 'Generated by create-nx-workspace',
  title: 'Welcome to file-drive',
};

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
        <ConvexClientProvider>
          <Toaster />
          <Header />
          {children}
          <Footer />
        </ConvexClientProvider>
      </body>
    </html>
  );
}
